export const PROFILES = {
	linkedin: "https://www.linkedin.com/in/gokercebeci/",
	github: "https://github.com/gokerDEV",
	behance: "https://behance.com/gokerART",
	facebook: "https://www.facebook.com/goker.art",
	// twitter: "https://twitter.com/gokercebeci",
	twitter: "https://twitter.com/gokerDEV",
	instagram: "https://instagram.com/goker.me",
	steam: "https://steamcommunity.com/id/gokerGAME",
	// twitch: 'https://www.twitch.tv/gokerESO',
	youtube: "https://youtube.com/@gokerDEV",
	vimeo: "https://vimeo.com/gokerART",
	dribbble: "https://dribble.com/goker",
	"500px": "https://500px.com/goker",
	stackoverflow: "https://stackoverflow.com/users/440140/goker",
	jsfiddle: "https://jsfiddle.net/user/goker",
	"product-hunt": "https://www.producthunt.com/@gokerDEV",
	etsy: "https://etsy.com/shop/goker",
	thenounproject: "https://thenounproject.com/goker",
	myminifactory: "https://www.myminifactory.com/users/goker",
	// tiktok: 'https://www.tiktok.com/@goker.me',
	pinterest: "www.pinterest.com/gokerART",
	medium: "https://medium.com/@gokerDEV",
	devto: "https://dev.to/gokerDEV",
	codepen: "https://codepen.io/goker",
	codeberg: "https://codeberg.org/goker",
	// codesandbox: 'https://codesandbox.io/u/goker',
	gitlab: "https://gitlab.com/goker",
	// bitbucket: 'https://bitbucket.org/goker',
	// hackerank: 'https://www.hackerrank.com/goker',
	// leetcode: 'https://leetcode.com/kodkafa/',
	// w3schools: 'https://www.w3profile.com/goker',
	// codecademy: 'https://www.codecademy.com/profiles/goker',

	orchid: "https://orcid.org/0000-0002-1853-6538",
	googlescholar: "https://scholar.google.com/citations?user=jvCzD28AAAAJ&hl=en",
	academia: "https://yildiz.academia.edu/goker",
	elsevier: "https://www.scopus.com/authid/detail.uri?authorId=57215312716",
	webofscience: "https://www.webofscience.com/wos/author/record/MIJ-8707-2025",
	huggingface: "https://huggingface.co/goker",
	npm: "https://www.npmjs.com/~goker",
	pypi: "https://pypi.org/user/goker/",
};
